schema:
  desc : Simple Example - with extension types 
  type : map
  map:
    my_string  : { type : str  } 
    my_int     : { type : int  }
    my_long    : { type : long }
    my_duration: { type : duration }

